Tinkering with the flow for signing.
I've hit a problem where openpgpjs won't sign, and I don't know why.  Is it a bug in openpgpjs?

It crashes at openpgpjs's cleartext.js:86, with "privateKeys[i].isPublic is not a function".  By inserting debugging statements, I've found that, while privateKeys[i].isPublic is indeed not a function, privateKeys[i].key.isPublic is.  Have I passed in something wrong, or is there a bug in openpgpjs?  Perhaps I have not actually decrypted the privateKey like I think I did, and that's why isPublic isn't where the signDetached function expects it?